In [274]:
import numpy as np

# WHAT IS NUMPY?
NumPy is a Python library used for working with arrays.

# WHY USE NUMPY?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [275]:
np.__version__

'1.26.4'

# CREATION OF NUMPY ARRAY

In [276]:
arr = np.array([25,25,40,50,60])
arr

array([25, 25, 40, 50, 60])

In [277]:
type(arr)

numpy.ndarray

# HOW TO DIMENSIONS OF AN NUMPY ARRAY?

In [278]:
arr.ndim

1

In [279]:
arr.size

5

In [280]:
len(arr)

5

In [281]:
arr.shape

(5,)

In [282]:
arr.dtype

dtype('int32')

# TYPECASTING OF AN NUMPY ARRAY

In [283]:
arr = np.array([25,25,40,50,60, 27.1, 'hello'])
arr

array(['25', '25', '40', '50', '60', '27.1', 'hello'], dtype='<U32')

In [ ]:
arr.dtype

dtype('<U32')

dtype('<U32')

In [ ]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [ ]:
arr[-3:]

array([40, 50, 60])

In [ ]:
arr * 10

array([250, 100, 200, 300, 400, 500, 600])

In [ ]:
sum(arr) # sum of the array

235

In [ ]:
np.mean(arr) # mean of the array

33.57142857142857

In [ ]:
np.median(arr) # median of the array

30.0

In [ ]:
# mode of the numpy array
from scipy import stats as st
import numpy as np

# creating an array using array() method
abc = np.array([1, 1, 2, 2, 2, 3, 4, 5])

# applying mode operation on array and 
# printing result
print(st.mode(abc))



ModeResult(mode=2, count=3)


# RANDOM FUNCTION

In [ ]:
np.random.randint(1,9)

4

In [ ]:
# CREATE A NUMPY ARRAY with 500 random integers between 1 to 449
arr=np.random.randint(1,450,500)
arr

array([ 64, 127, 311, 252, 110, 284, 350, 194, 298, 426, 435,  95, 133,
       321,  76,  21, 314, 311, 438, 386, 147, 422,  69,  55, 196, 291,
        28, 157, 352, 215, 439, 297, 445, 202, 443, 357, 299, 284, 312,
       437, 148, 251, 263, 288, 267, 447, 424, 353,  10, 311, 374, 210,
       340, 123,  81, 204, 258, 313, 119, 309, 442, 254,  87, 114,  82,
        17, 228,  16, 437, 267,  92, 192, 112, 426, 417, 220, 261,  66,
       111, 255, 301,  51, 280, 322, 348, 173, 277, 415, 157, 278,  16,
        53,  49, 234, 429, 401, 373,  13,  39, 351, 159, 220, 289, 101,
       254, 118, 311,  79, 355, 427,  63, 350, 444, 194,  73, 374, 434,
       178, 160, 170, 319, 109,  94, 436, 430, 407, 183, 381, 147, 419,
       437, 193,  58, 339, 372, 226, 354, 428, 168,  80,   7, 247, 273,
        34, 139, 409, 357, 185,   2, 252, 149, 216, 246, 374,  45, 316,
       262, 422, 378, 356, 355,  94, 318, 170,   5, 157, 132, 127, 198,
       246,  31, 152, 436, 183, 194, 228, 348, 317, 259, 352, 23

In [ ]:
# count the number less than 100 in the array
def lessthan100():
    numbers=arr[arr<100]
    print(numbers)

lessthan100()

[64 95 76 21 69 55 28 10 81 87 82 17 16 92 66 51 16 53 49 13 39 79 63 73
 94 58 80  7 34  2 45 94  5 31 27  4 67 59 80 50 94 12 82 46 33 45 58 41
 70  2  3 77 72 14 72 48 17 89 28 63 28  5 47 33 94 91  1  9 87 59 14 60
 68 12 72  7 49 40 53 66 34 10 16 10  1 12 30 96 37 17  9 50 86 17 18 95
 14 42 97 76 99 40]


In [ ]:
# count the even number present in the array
arr=np.random.randint(1,450,500)

evenno=arr[arr % 2 ==0]
evencount=len(evenno)
print(evenno)
print( "NO. OF EVEN COUNT: ", evencount)

[ 54 390 118 348  98  80 306 192 422  46 410 244 122 104 186 386  78  88
 398 316 212 144 138 414 366 362 240 206 422 160  62 440 214 222 216 196
 396  30 182 146 326 158 356 384 134 226 208  70 194 184 134 100 298 414
 366 102 194 208 366 134 228  92 264 162 418 126 336 270 346 210 268  86
 352  78 210 336 180 384 304 222 224 332 356 312 216  62  64 232 116 214
 342 130 336 402 218 388 142 342 362  28  62 178 300  18  28 332 384 200
 414 180 116 210  44 312 250  46 232 414 372  48 414 228 246  52 162 378
 312 314 244 380 262 126 376 218 232 394 438  32 250 212  94  26 242  18
  92 152 204  30 218 194 424 308 422 200 426 280 178 422 400 274 262 308
  68 216 380 152  70 282 430  40 444 106 264 398 378  42 140 358  30 256
 322 222 140  90 262 198  92 350 146 296 320 150 104  38 374 188  14  48
 318  26 174 164 104 240  72 412 180 320  30 288 268  96 198  40 108 148
 442 102 218 360 122 336 144 178  64 444 368  86 226 302 242 422 424 252
 184 386 224 274  56  48 160 180 428 272 130 320 14

 # 2 DIMENSIONAL ARRAY

In [ ]:
ls = [[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr2= np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[0] 

array([1, 2, 3])

In [ ]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[-1]

array([7, 8, 9])

In [ ]:
arr2[-3:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
arr2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[-2:,-3:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

# INSTANT FUNCTION

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

# 3 DIMENSIONAL

In [ ]:
ls=[[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]]

In [ ]:
arr3=np.array(ls)
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(4, 3, 3)

In [ ]:
arr3[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3[-1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr3[0:4,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr3[:,-3,-3:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr3[2,1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr3[0,1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr3[-3,-2:,-2:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr3[:,1:,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [ ]:
arr3[-4:,-2:,-2:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [ ]:
arr3[:,-1,::-1]

array([[9, 8, 7],
       [9, 8, 7],
       [9, 8, 7],
       [9, 8, 7]])

In [ ]:
arr3.ravel() # CONVERT 3D TO 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3.shape

(4, 3, 3)

In [ ]:
arr3.reshape(36,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# NUMPY ARRAY JOIN

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # axis=1=column,axis=0=row

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# hstack and vstack

In [ ]:
# hstack join the arrray in the horizontal way
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
# vstack join the array in the vertical way
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

arr

array([[1, 2, 3],
       [4, 5, 6]])

# NUMPY COPY AND VIEW
The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
# COPY
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# ARGMIN
The argmin function in NumPy returns the indices of the minimum values along an axis. If you have an array and you want to know the position of the smallest value, argmin is the function to use.

In [ ]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

# Find the index of the minimum value
min_index = np.argmin(array)

print("Array:", array)
print("Index of minimum value:", min_index)
print("Minimum value:", array[min_index])


Array: [3 1 4 1 5 9 2 6 5]
Index of minimum value: 1
Minimum value: 1


# ARGMAX
The argmax function in NumPy is used to find the index of the maximum value in an array. This function can be particularly useful when you need to know the position of the largest element in an array.

In [ ]:
array = np.array([5, 3, 6, 2, 8, 1])

# Find the index of the maximum value
max_index = np.argmax(array)

print("Array:", array)
print("Index of maximum value:", max_index)
print("Maximum value:", array[max_index])


Array: [5 3 6 2 8 1]
Index of maximum value: 4
Maximum value: 8


# ARGSORT
The argsort function in NumPy is used to get the indices that would sort an array. This is particularly useful when you need to sort an array but want to keep track of the original indices of the elements.

In [ ]:
array = np.array([5, 3, 6, 2, 8, 1])

indexsort=arr.argsort()
indexsort


array([1, 2, 3, 4, 0], dtype=int64)